name: shared_component
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  google_ui:
    git:
      url: "git@github.com:JimmysonJack/google_ui.git"
      ref: master
  flutter:
    sdk: flutter
  slidy: ^3.2.2+2
  shared_preferences: ^2.0.15
  flutter_breadcrumb: ^1.0.1
  flutter_svg: ^1.1.0
  dio: ^4.0.6
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  gql_http_link: ^0.4.2
  ferry: ^0.10.5-dev.3
  ferry_hive_store: ^0.4.4
  ferry_flutter: ^0.5.4
  syncfusion_flutter_datepicker: ^20.1.56
  syncfusion_flutter_pdfviewer: ^20.1.56-beta
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0


dependency_overrides:
  rxdart: ^0.27.4

dev_dependencies:
  flutter_modular: ^5.0.3
  mobx: ^2.0.7+4
  mobx_codegen: ^2.0.7
  modular_test: ^2.0.0
  build_runner: ^2.1.11
  flutter_mobx: ^2.0.6+1
  # file cross picker starts here
  file_selector_windows: ^0.0.2
  path_provider: ^2.0.2
  package_info: ^2.0.1
  share: ^2.0.2
  disk_space: ^0.2.1
  file_picker: ^4.1.3
  http_parser: ^4.0.0
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  #ends here

  ferry_generator: ^0.5.0-dev.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/file.svg
    - assets/empty.svg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
